### ISSUE TITLE
Consider making Command a var

### ISSUE THREAD

**Issue by saurori** [d4l3k/go-pbzip2#1]
Would it be possible to change the [Command const](https://github.com/d4l3k/go-pbzip2/blob/master/pbzip2.go#L15) to a var to allow setting at a package level? This would allow:
 - Changing the library to a compatible equivalent such as [lbzip2](http://lbzip2.org/)
 - Setting other optional flags such as compression block size

The alternative is to create a config struct passed to `NewWriter`/`NewReader`.

**Comment by d4l3k** [comment]
I'd personally prefer a config variant like NewWriterConfig, but I'm okay
with either. Feel free to send a pull request!

**Comment by saurori** [comment]
Great! I can put something together shortly or by next week.

**Comment by saurori** [comment]
I've opened a PR here: https://github.com/d4l3k/go-pbzip2/pull/2

Also please consider versioning the library with releases (semver).
